### ISSUE TITLE
Terminal backend question

### ISSUE THREAD

**Issue by lesleyrs** [file-acomplaint/kakikun#4]
Do you remember why you chose `termion` backend for Linux instead of `crossterm`? I know this was a while back so it might not be that relevant today, but just curious is all.

**Comment by lesleyrs** [comment]
I tried both executables but didn't see a noticeable difference between `crossterm` on windows and `termion` on WSL when comparing skipped pixels.

Also wasn't able to get it to work completely when compiling btw, you didn't commit the lock file which you should here since it's a binary crate. When changing `cursive_buffered_backend` version or fixing the errors it will run but some things don't show up in the drawing screen. Not sure why since there weren't any errors.

Lastly there's a typo on the opening screen `langauges` -> `languages` (I didn't want to make a pr just for this when I can't even get it to work right)

**Comment by file-acomplaint** [comment]
I see, forgive my rookie mistakes there! I will have a look and correct this in the coming days.

**Comment by file-acomplaint** [comment]
Done! You were absolutely right that `crossterm `and `termion` aren't different, so I changed to crossterm across the board. Thanks again!
